/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace INFTHolderVesting {
  export type VestingPositionStruct = {
    amount: PromiseOrValue<BigNumberish>;
    amountClaimed: PromiseOrValue<BigNumberish>;
    startTimestamp: PromiseOrValue<BigNumberish>;
  };

  export type VestingPositionStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    amount: BigNumber;
    amountClaimed: BigNumber;
    startTimestamp: BigNumber;
  };
}

export interface INFTHolderVestingInterface extends utils.Interface {
  functions: {
    "availableToClaim(uint256,uint256)": FunctionFragment;
    "claimTokens(uint256[])": FunctionFragment;
    "getVestingPositions(uint256)": FunctionFragment;
    "getVestingSchedule(uint256)": FunctionFragment;
    "vestTokens(uint256[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "availableToClaim"
      | "claimTokens"
      | "getVestingPositions"
      | "getVestingSchedule"
      | "vestTokens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "availableToClaim",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTokens",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getVestingPositions",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getVestingSchedule",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "vestTokens",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "availableToClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVestingPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVestingSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vestTokens", data: BytesLike): Result;

  events: {
    "TokensClaimed(address,uint256,uint256)": EventFragment;
    "TokensVested(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TokensClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokensVested"): EventFragment;
}

export interface TokensClaimedEventObject {
  _buyer: string;
  positionIndex: BigNumber;
  amount_: BigNumber;
}
export type TokensClaimedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  TokensClaimedEventObject
>;

export type TokensClaimedEventFilter = TypedEventFilter<TokensClaimedEvent>;

export interface TokensVestedEventObject {
  _buyer: string;
  positionIndex: BigNumber;
  amount_: BigNumber;
}
export type TokensVestedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  TokensVestedEventObject
>;

export type TokensVestedEventFilter = TypedEventFilter<TokensVestedEvent>;

export interface INFTHolderVesting extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: INFTHolderVestingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    availableToClaim(
      _id: PromiseOrValue<BigNumberish>,
      _timestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    claimTokens(
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getVestingPositions(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[INFTHolderVesting.VestingPositionStructOutput[]]>;

    getVestingSchedule(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], BigNumber[]] & {
        timestamps: BigNumber[];
        amounts: BigNumber[];
      }
    >;

    vestTokens(
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  availableToClaim(
    _id: PromiseOrValue<BigNumberish>,
    _timestamp: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  claimTokens(
    _ids: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getVestingPositions(
    _id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<INFTHolderVesting.VestingPositionStructOutput[]>;

  getVestingSchedule(
    _id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber[], BigNumber[]] & {
      timestamps: BigNumber[];
      amounts: BigNumber[];
    }
  >;

  vestTokens(
    _ids: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    availableToClaim(
      _id: PromiseOrValue<BigNumberish>,
      _timestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimTokens(
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    getVestingPositions(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<INFTHolderVesting.VestingPositionStructOutput[]>;

    getVestingSchedule(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], BigNumber[]] & {
        timestamps: BigNumber[];
        amounts: BigNumber[];
      }
    >;

    vestTokens(
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "TokensClaimed(address,uint256,uint256)"(
      _buyer?: PromiseOrValue<string> | null,
      positionIndex?: PromiseOrValue<BigNumberish> | null,
      amount_?: PromiseOrValue<BigNumberish> | null
    ): TokensClaimedEventFilter;
    TokensClaimed(
      _buyer?: PromiseOrValue<string> | null,
      positionIndex?: PromiseOrValue<BigNumberish> | null,
      amount_?: PromiseOrValue<BigNumberish> | null
    ): TokensClaimedEventFilter;

    "TokensVested(address,uint256,uint256)"(
      _buyer?: PromiseOrValue<string> | null,
      positionIndex?: PromiseOrValue<BigNumberish> | null,
      amount_?: PromiseOrValue<BigNumberish> | null
    ): TokensVestedEventFilter;
    TokensVested(
      _buyer?: PromiseOrValue<string> | null,
      positionIndex?: PromiseOrValue<BigNumberish> | null,
      amount_?: PromiseOrValue<BigNumberish> | null
    ): TokensVestedEventFilter;
  };

  estimateGas: {
    availableToClaim(
      _id: PromiseOrValue<BigNumberish>,
      _timestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimTokens(
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getVestingPositions(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVestingSchedule(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vestTokens(
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    availableToClaim(
      _id: PromiseOrValue<BigNumberish>,
      _timestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimTokens(
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getVestingPositions(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVestingSchedule(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vestTokens(
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
