/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFreeMintable,
  IFreeMintableInterface,
} from "../../../contracts/interfaces/IFreeMintable";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_numberOfTokens",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
    ],
    name: "freeMint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFreeMintable__factory {
  static readonly abi = _abi;
  static createInterface(): IFreeMintableInterface {
    return new utils.Interface(_abi) as IFreeMintableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFreeMintable {
    return new Contract(address, _abi, signerOrProvider) as IFreeMintable;
  }
}
