/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITokenWithLevel,
  ITokenWithLevelInterface,
} from "../../../contracts/interfaces/ITokenWithLevel";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "getLevelOfTokenById",
    outputs: [
      {
        internalType: "uint256",
        name: "level_",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITokenWithLevel__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenWithLevelInterface {
    return new utils.Interface(_abi) as ITokenWithLevelInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenWithLevel {
    return new Contract(address, _abi, signerOrProvider) as ITokenWithLevel;
  }
}
